# Generated by Django 3.1.12 on 2024-12-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusId', models.CharField(max_length=5)),
                ('CarPlateNo', models.CharField(max_length=7)),
                ('Capacity', models.IntegerField()),
                ('IsActive', models.BooleanField()),
            ],
            options={
                'db_table': 'Bus',
            },
        ),
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScheduleId', models.CharField(max_length=5)),
                ('DepartureTime', models.TimeField()),
                ('ArrivalTime', models.TimeField()),
                ('DayOfWeek', models.IntegerField(choices=[(0, 'SUNDAY'), (1, 'MONDAY'), (2, 'TUESDAY'), (3, 'WEDNESDAY'), (4, 'THURSDAY'), (5, 'FRIDAY'), (6, 'SATURDAY')])),
            ],
            options={
                'db_table': 'BusSchedule',
            },
        ),
        migrations.CreateModel(
            name='BusScheduleAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssignmentId', models.CharField(max_length=5)),
                ('ScheduleId', models.CharField(max_length=5)),
                ('RouteId', models.CharField(max_length=5)),
                ('BusId', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'BusScheduleAssignment',
            },
        ),
        migrations.CreateModel(
            name='BusStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StationId', models.CharField(max_length=5)),
                ('StationName', models.CharField(max_length=255)),
                ('StationLocation', models.TextField()),
                ('IsActive', models.BooleanField()),
            ],
            options={
                'db_table': 'BusStation',
            },
        ),
        migrations.CreateModel(
            name='BusTrackingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArrivalDateTime', models.DateTimeField()),
                ('AssignmentId', models.CharField(max_length=5)),
                ('BusStatus', models.CharField(choices=[('HA', 'HAVENT ARRIVE'), ('A', 'ARRIVE'), ('D', 'DROPING'), ('R', 'RESTING'), ('W', 'WAITING')], max_length=5)),
                ('BusCapacityEstimate', models.CharField(choices=[('E', 'EMPTY'), ('L', 'LOW'), ('M', 'MODERATE'), ('AF', 'ALMOST FULL'), ('F', 'FULL')], max_length=5)),
            ],
            options={
                'db_table': 'BusTrackingLog',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RouteId', models.CharField(max_length=5)),
                ('RouteDescription', models.TextField()),
                ('IsActive', models.BooleanField()),
                ('FromCampus', models.BooleanField()),
            ],
            options={
                'db_table': 'Route',
            },
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StationId', models.CharField(max_length=5)),
                ('RouteId', models.CharField(max_length=5)),
                ('RouteDuration', models.IntegerField()),
                ('RouteOrder', models.IntegerField()),
            ],
            options={
                'db_table': 'RouteStation',
            },
        ),
    ]
