database: 
  type: mongodb
  host: cluster0.0htcf.mongodb.net
  database_name: my_database
  options: "?retryWrites=true&w=majority&appName=Cluster0"
collections: ["Bus", "BusSchedule", "BusStation", "Route", "RouteStation", "BusScheduleAssignment", "BusTrackingLog"]